# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  publish: 
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]
         
      
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with: 
        dotnet-version: 5.0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: dotnet restore 
       
    - name: Build
      run: |
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -o ./AppTramitesNoPension0423 -r win-x64 --self-contained true -p:PublishReadyToRun=false
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: website
        path: ./AppTramitesNoPension0423
        if-no-files-found: error
 
